// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlaybackDevice(arg1, arg2) {
  return window['go']['main']['App']['AddPlaybackDevice'](arg1, arg2);
}

export function AddServer(arg1, arg2) {
  return window['go']['main']['App']['AddServer'](arg1, arg2);
}

export function CheckServerConnection(arg1) {
  return window['go']['main']['App']['CheckServerConnection'](arg1);
}

export function ConnectToAudioServer(arg1) {
  return window['go']['main']['App']['ConnectToAudioServer'](arg1);
}

export function DisableServer() {
  return window['go']['main']['App']['DisableServer']();
}

export function DisconnetFromAudioServer(arg1) {
  return window['go']['main']['App']['DisconnetFromAudioServer'](arg1);
}

export function EnableServer() {
  return window['go']['main']['App']['EnableServer']();
}

export function GetClientConfig() {
  return window['go']['main']['App']['GetClientConfig']();
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetServerEnabled() {
  return window['go']['main']['App']['GetServerEnabled']();
}

export function GetServerList() {
  return window['go']['main']['App']['GetServerList']();
}

export function ListAudioDevices() {
  return window['go']['main']['App']['ListAudioDevices']();
}

export function MinimiseApp() {
  return window['go']['main']['App']['MinimiseApp']();
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RemovePlaybackDevice(arg1, arg2) {
  return window['go']['main']['App']['RemovePlaybackDevice'](arg1, arg2);
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function ReorderServers(arg1) {
  return window['go']['main']['App']['ReorderServers'](arg1);
}

export function SaveClientConfig(arg1) {
  return window['go']['main']['App']['SaveClientConfig'](arg1);
}

export function SaveServerConfig(arg1) {
  return window['go']['main']['App']['SaveServerConfig'](arg1);
}

export function SetServerRemoteDevice(arg1, arg2) {
  return window['go']['main']['App']['SetServerRemoteDevice'](arg1, arg2);
}

export function UpdatePlaybackDevice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePlaybackDevice'](arg1, arg2, arg3, arg4);
}

export function UpdateServerSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateServerSettings'](arg1, arg2);
}
