// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {wcatools} from '../models';
import {pcmresample} from '../models';

export function AddPlaybackDevice(arg1:string,arg2:string):Promise<void>;

export function AddServer(arg1:string,arg2:string):Promise<void>;

export function CheckServerConnection(arg1:string):Promise<void>;

export function ConnectToAudioServer(arg1:string):Promise<void>;

export function DisableServer():Promise<void>;

export function DisconnetFromAudioServer(arg1:string):Promise<void>;

export function EnableServer():Promise<void>;

export function GetAppSettings():Promise<main.AppSettings>;

export function GetClientConfig():Promise<main.ClientConfig>;

export function GetConfigDir():Promise<string>;

export function GetLastActiveMode():Promise<string>;

export function GetServerConfig():Promise<main.ServerConfig>;

export function GetServerEnabled():Promise<boolean>;

export function GetServerList():Promise<Array<main.Server>>;

export function ListAudioDevices():Promise<Array<wcatools.AudioConfig>>;

export function MinimiseApp():Promise<void>;

export function OpenConfigDir():Promise<void>;

export function QuitApp():Promise<void>;

export function RemovePlaybackDevice(arg1:string,arg2:string):Promise<void>;

export function RemoveServer(arg1:string):Promise<void>;

export function ReorderServers(arg1:Array<string>):Promise<void>;

export function SaveAppSettings(arg1:main.AppSettings):Promise<void>;

export function SaveClientConfig(arg1:main.ClientConfig):Promise<void>;

export function SaveLastActiveMode(arg1:string):Promise<void>;

export function SaveServerConfig(arg1:main.ServerConfig):Promise<void>;

export function SetServerRemoteDevice(arg1:string,arg2:string):Promise<void>;

export function UpdatePlaybackDevice(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<void>;

export function UpdateServerSettings(arg1:string,arg2:pcmresample.Options):Promise<void>;
